### ISSUE TITLE
:bug: The Container holding the table is not responsive in mobile view

### ISSUE THREAD

**Issue by Adyasha8105** [chakra-ui/chakra-ui-docs#160] opened 2021-12-19 17:16 UTC
### Description

The table box is not responsive on the main page. It's a minor bug and I can fix this.

### Link to Reproduction

https://chakra-ui.com/docs/data-display/table

### Steps to reproduce

1. Go to the [link](https://chakra-ui.com/docs/data-display/table) and see the page in 320px i.e mobile view

Screenshot: <img width="569" alt="Screenshot 2021-12-19 at 10 45 01 PM" src="https://user-images.githubusercontent.com/54095539/146684191-f269bce4-de71-4574-8078-b9693b1c4ad4.png">

### Chakra UI Version

1.14.1

### Operating System

macOS

**Comment by Adyasha8105** [comment] 2021-12-21 16:42
Yes, am looking for a rearranging thing. But okay I got it. Thanks, @primos63 :D 
And I will fix the `overflow` property in the container.

**Comment by primos63** [comment] 2021-12-21 19:08
@Adyasha8105 as you wish. It's an open source project. PRs welcome and great PRs most welcome! :)  I don't believe anyone is working on it at the moment.

**Comment by nikolovlazar** [comment] 2021-12-21 19:10
@primos63 indeed. @Adyasha8105 you want me to assign this to you?

**Comment by Adyasha8105** [comment] 2021-12-21 19:13
@primos63 agreed!! @nikolovlazar yes you can assign it to me 😀

**Comment by nikolovlazar** [comment] 2022-03-11 07:49
Hello @Adyasha8105! Do you still feel like you want to work on this issue? It's okay if you don't have time. Life happens 😁 Let me know.

**Comment by TylerAPfledderer** [comment] 2022-03-12 03:35
Hey @nikolovlazar! 

I can jump in on this if @Adyasha8105 is no longer able to.

**Comment by TylerAPfledderer** [comment] 2022-03-18 22:05
@nikolovlazar to go along with issue #447 that @noobinthisgame recently posted, could the examples in the example code just be wrapped in the `TableContainer` component which provides
```
overflow-x: auto;
overflow-y: hidden;
```
or consider globally altering the live preview container as suggested above for all doc pages?

**Comment by nikolovlazar** [comment] 2022-03-19 06:36
@TylerAPfledderer I still haven't taken a better look into this, but just off the top of my head the second option makes more sense.

**Comment by TylerAPfledderer** [comment] 2022-03-19 14:32
@nikolovlazar I agree! I can look into this along with adding the docs for the `TableContainer`.

**Comment by noobinthisgame** [comment] 2022-03-21 20:58
@TylerAPfledderer I would wrap the examples in the `TableContainer`. Like we do not need a separate example. Just comment the purpose of the `TableContainer` in the first usage :)

**Comment by TylerAPfledderer** [comment] 2022-03-21 21:10
> @nikolovlazar @TylerAPfledderer I would wrap the table examples in the `TableContainer`. Like this we do not need a separate example. Just comment the purpose of the `TableContainer` in the first usage :)
> 
> I would also use the `TableContainer` on all Tables in the docs that need it.

@noobinthisgame You got it! I'll leave the PR about the `TableContainer` doc in draft until that is updated.

To your second point, do you mean doing this instead of applying `overflow: auto` to the live preview container?

**Comment by noobinthisgame** [comment] 2022-03-21 21:43
@TylerAPfledderer Let's wait if @nikolovlazar agrees with me :D

**Comment by nikolovlazar** [comment] 2022-03-27 19:53
Let's roll with TableContainer.

**Comment by TylerAPfledderer** [comment] 2022-03-28 12:58
@nikolovlazar Moved PR #454 to `Open`. This will resolve overflow issues in the `Table` docs, but I will check the rest of the site for other live examples showing overflow in mobile.

**Comment by TylerAPfledderer** [comment] 2022-03-28 13:14
@nikolovlazar I've already found an issue in the Flex Docs example [Flex and Spacer vs Grid vs Stack](https://chakra-ui.com/docs/components/layout/flex#flex-and-spacer-vs-grid-vs-stack). But fixing the overflow causes the example to not appear as intended in mobile (The demonstration of `Flex and Spacer` no longer has space between the boxes).

Do you recommend I handle the overflow as one issue (including other examples that I find), and the example itself as a separate issue?

**Comment by nikolovlazar** [comment] 2022-03-29 06:09
@TylerAPfledderer feel free to open a new issue for those cases. For now, I'll close this issue since your PR fixed it.

**Closed by nikolovlazar** 2022-03-29 06:09 UTC
Labels: bug
